module.exports = [
    {
    name: 'LeBron James',
    position: 'Small Forward',
    ppg: 27.1,
    rbg: 7.5,
    apg: 7.4,
    fgp: .50,
    height: "6'9",
    weight: 250,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAccitSJk-DpAO47XuvUaFz4b_g6z_tfdj7pB2VdGMCXHIQPHAl49DU9voA_g6BmxF6zM&usqp=CAU',
    },
    {
        name: 'Stephen Curry',
        position: 'point guard',
        ppg: 24.3,
        rbg: 5.6,
        apg: 6.5,
        fgp: .47,
        height: "6'2",
        weight: 185,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQJTJ6qy7vu0-XtvhSIDecv9v81834yoxdpA&usqp=CAU',
    },
    {
        name: 'Ja Morant', 
        position: 'shooting guard',
        ppg: 21.1,
        rbg: 4.5,
        apg: 7.1,
        fpg: .47,
        height: "6'2",
        weight: 175,
        img: 'https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/7JQPEGWGHAI6ZDH7GOYFT5GBW4.jpg&w=1440',
    },
    {
        name: 'Paolo Banchero',    
        position: 'Power Forward',
        ppg: 23.5,
        rpg: 8.3,
        apg: 3.6,
        fgp: .46,
        height: "9'10",
        weight: 250,
        img: 'https://s7d2.scene7.com/is/image/TWCNews/100722_n13_bancherovsmavs2_10102022',
    },
    {
        name: 'Giannis Antetokounmpo', 
        position: 'Center',
        ppg: 29.5,
        rbg: 12.0,
        apg: 5.3,
        fgp: .54,
        height: "6'10",
        weight: 243,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdDPNm11Rq3vGiQx7kjunXHGhoHS9LJ9lzY0S_vqAs54qYQZv4RcN-vlyz6TYbinxG5Lw&usqp=CAU',
    }
]
